/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Controllers.ImportDataControl;
import Controllers.UpdateDataControl;
import java.awt.GraphicsEnvironment;
import java.awt.MouseInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime ;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Frame extends javax.swing.JFrame {
   
    /**
     * Creates new form Frame
     */
    public Frame() {
        
        initComponents();
        this.setIconImage( new javax.swing.ImageIcon( /*java.awt.Toolkit.getDefaultToolkit().*/getClass().getResource("/iptaskmanager/Images/JarLogo.png")).getImage()  ); // NOI18N
        
        new Timer (1000, new ActionListener()
        { 
            public void actionPerformed(ActionEvent e)
        {   LocalDateTime ldt = LocalDateTime.now() ;
            
            int hh = ldt.getHour() ;
            String h = String.valueOf( hh ) ;
            if ( hh<10 ) 
                h = '0'+h ;
            HOUR.setText(h) ;
            
            int mn = ldt.getMinute() ;
            String m = String.valueOf( mn ) ;
            if ( mn<10 ) 
                m = '0'+m ;
            MINUTE.setText(m) ;
            
            int ss = ldt.getSecond() ;
            String s = String.valueOf( ss ) ;
            if ( ss<10 ) 
                s = '0'+s ;
            SECOND.setText(s) ;
            
            int dd = ldt.getDayOfMonth() ;
            String ddy = String.valueOf( dd ) ;
            if ( dd<10 ) 
                ddy = '0'+ddy ;
            DAY.setText(ddy) ;
            
            
            
            int mth = ldt.getMonthValue() ;
            String mmth = String.valueOf(mth) ;
            if ( mth<10 ) 
                mmth = '0'+mmth ;
            MONTH.setText(mmth) ;
            
            
            YEAR.setText(String.valueOf( ldt.getYear() )) ;
            
            
            
        }
            
        }).start() ;
        
        TaskManagerPage.setVisible(false) ;
        StatisticsPage.setVisible(false);
        
        
        
        String[] all = { "Done", "In progress","Not yet" } ;
        for ( String item : all )
            {
               State.addItem(item) ;
               
            }
        State.setSelectedIndex(-1);
        
        loadInitial();
    }
    
    static boolean Maximized = true ;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        LayeredPane = new javax.swing.JPanel();
        HomePage = new javax.swing.JPanel();
        WelcomePanel1 = new javax.swing.JPanel();
        Welcome1 = new javax.swing.JLabel();
        Welcome4 = new javax.swing.JLabel();
        MyScrollPane1 = new javax.swing.JScrollPane();
        ComingSoonTable = new javax.swing.JTable();
        TaskManagerPage = new javax.swing.JPanel();
        WelcomePanel3 = new javax.swing.JPanel();
        Welcome3 = new javax.swing.JLabel();
        MyScrollPane = new javax.swing.JScrollPane();
        TaskTable = new javax.swing.JTable();
        EditingBar = new javax.swing.JPanel();
        TaskID = new javax.swing.JTextField();
        Task = new javax.swing.JTextField();
        Date = new javax.swing.JFormattedTextField();
        Deadline = new javax.swing.JFormattedTextField();
        PIC = new javax.swing.JTextField();
        State = new javax.swing.JComboBox<>();
        ButtonBar = new javax.swing.JPanel();
        CREATE = new javax.swing.JLabel();
        Save = new javax.swing.JLabel();
        Update = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Search = new javax.swing.JLabel();
        StatisticsPage = new javax.swing.JPanel();
        WelcomePanel2 = new javax.swing.JPanel();
        Welcome2 = new javax.swing.JLabel();
        BGPanel = new javax.swing.JPanel();
        DoneRatio = new javax.swing.JProgressBar();
        LookList = new javax.swing.JLabel();
        LookList1 = new javax.swing.JLabel();
        InProgressRatio = new javax.swing.JProgressBar();
        LookList2 = new javax.swing.JLabel();
        NotYetRatio = new javax.swing.JProgressBar();
        Menu = new javax.swing.JPanel();
        IPLogoLabel = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        Home1 = new javax.swing.JLabel();
        TaskManagerPanel = new javax.swing.JPanel();
        TaskManager = new javax.swing.JLabel();
        StatisticsPanel = new javax.swing.JPanel();
        Statistics = new javax.swing.JLabel();
        MySeparator1 = new javax.swing.JSeparator();
        MySeparator2 = new javax.swing.JSeparator();
        AtInsat = new javax.swing.JLabel();
        MadeWith = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HR = new javax.swing.JLabel();
        MIN = new javax.swing.JLabel();
        SEC = new javax.swing.JLabel();
        DAY = new javax.swing.JLabel();
        MONTH = new javax.swing.JLabel();
        YEAR = new javax.swing.JLabel();
        HOUR = new javax.swing.JLabel();
        SECOND = new javax.swing.JLabel();
        MINUTE = new javax.swing.JLabel();
        DAY1 = new javax.swing.JLabel();
        DAY2 = new javax.swing.JLabel();
        TopPanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        Screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BGMousePressed(evt);
            }
        });

        LayeredPane.setBackground(new java.awt.Color(255, 255, 255));
        LayeredPane.setLayout(new javax.swing.OverlayLayout(LayeredPane));

        HomePage.setBackground(new java.awt.Color(255, 255, 255));

        WelcomePanel1.setBackground(new java.awt.Color(180, 0, 0));

        Welcome1.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
        Welcome1.setForeground(new java.awt.Color(255, 255, 255));
        Welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/WelcomeHand.png"))); // NOI18N
        Welcome1.setText("WELCOME OUMAIMA !");
        Welcome1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Welcome1.setIconTextGap(15);

        javax.swing.GroupLayout WelcomePanel1Layout = new javax.swing.GroupLayout(WelcomePanel1);
        WelcomePanel1.setLayout(WelcomePanel1Layout);
        WelcomePanel1Layout.setHorizontalGroup(
            WelcomePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Welcome1)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        WelcomePanel1Layout.setVerticalGroup(
            WelcomePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Welcome1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Welcome4.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        Welcome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/notif.png"))); // NOI18N
        Welcome4.setText("These tasks should be accomplished by midnight");
        Welcome4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Welcome4.setIconTextGap(7);

        ComingSoonTable.setAutoCreateRowSorter(true);
        ComingSoonTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComingSoonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Task", "Date", "Deadline", "Person in charge", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ComingSoonTable.setGridColor(new java.awt.Color(255, 255, 255));
        ComingSoonTable.setIntercellSpacing(new java.awt.Dimension(10, 10));
        ComingSoonTable.setRowHeight(30);
        ComingSoonTable.setRowSelectionAllowed(true);
        ComingSoonTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        ComingSoonTable.setShowHorizontalLines(false);
        ComingSoonTable.setShowVerticalLines(false);
        ComingSoonTable.getTableHeader().setReorderingAllowed(false);
        ComingSoonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComingSoonTableMouseClicked(evt);
            }
        });
        MyScrollPane1.setViewportView(ComingSoonTable);

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addComponent(Welcome4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MyScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
                .addContainerGap())
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(WelcomePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Welcome4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        LayeredPane.add(HomePage);

        TaskManagerPage.setBackground(new java.awt.Color(255, 255, 255));

        WelcomePanel3.setBackground(new java.awt.Color(180, 0, 0));

        Welcome3.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
        Welcome3.setForeground(new java.awt.Color(255, 255, 255));
        Welcome3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/WelcomeHand.png"))); // NOI18N
        Welcome3.setText("WELCOME OUMAIMA !");
        Welcome3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Welcome3.setIconTextGap(15);

        javax.swing.GroupLayout WelcomePanel3Layout = new javax.swing.GroupLayout(WelcomePanel3);
        WelcomePanel3.setLayout(WelcomePanel3Layout);
        WelcomePanel3Layout.setHorizontalGroup(
            WelcomePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Welcome3)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        WelcomePanel3Layout.setVerticalGroup(
            WelcomePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Welcome3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TaskTable.setAutoCreateRowSorter(true);
        TaskTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Task", "Date", "Deadline", "Person in charge", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        TaskTable.setIntercellSpacing(new java.awt.Dimension(10, 10));
        TaskTable.setRowHeight(30);
        TaskTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TaskTable.getTableHeader().setReorderingAllowed(false);
        TaskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaskTableMousePressed(evt);
            }
        });
        MyScrollPane.setViewportView(TaskTable);

        EditingBar.setBackground(new java.awt.Color(255, 255, 255));
        EditingBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editing Bar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comfortaa", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        EditingBar.setForeground(new java.awt.Color(153, 0, 0));
        EditingBar.setLayout(new java.awt.GridLayout(1, 0));

        TaskID.setEditable(false);
        TaskID.setBackground(new java.awt.Color(255, 255, 255));
        TaskID.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        TaskID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TaskID.setText("TaskID");
        TaskID.setBorder(null);
        TaskID.setSelectionColor(new java.awt.Color(0, 0, 0));
        EditingBar.add(TaskID);

        Task.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        Task.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Task.setText("Task");
        Task.setBorder(null);
        EditingBar.add(Task);

        Date.setBorder(null);
        Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setText("yyyy-mm-dd");
        Date.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        Date.setSelectionColor(new java.awt.Color(0, 0, 0));
        EditingBar.add(Date);

        Deadline.setBorder(null);
        Deadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        Deadline.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Deadline.setText("yyyy-mm-dd");
        Deadline.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        Deadline.setSelectionColor(new java.awt.Color(0, 0, 0));
        EditingBar.add(Deadline);

        PIC.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        PIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PIC.setText("Person in charge");
        PIC.setBorder(null);
        EditingBar.add(PIC);

        State.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        State.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditingBar.add(State);

        ButtonBar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Button Bar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comfortaa", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        ButtonBar.setLayout(new java.awt.GridLayout(1, 0));

        CREATE.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        CREATE.setForeground(new java.awt.Color(153, 0, 0));
        CREATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CREATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Create.png"))); // NOI18N
        CREATE.setLabelFor(ButtonBar);
        CREATE.setText("CREATE");
        CREATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CREATE.setIconTextGap(5);
        CREATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CREATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CREATEMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CREATEMousePressed(evt);
            }
        });
        ButtonBar.add(CREATE);

        Save.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        Save.setForeground(new java.awt.Color(153, 0, 0));
        Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/SAVE.png"))); // NOI18N
        Save.setLabelFor(ButtonBar);
        Save.setText("SAVE");
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.setIconTextGap(5);
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaveMousePressed(evt);
            }
        });
        ButtonBar.add(Save);

        Update.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(153, 0, 0));
        Update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Update.png"))); // NOI18N
        Update.setLabelFor(ButtonBar);
        Update.setText("UPDATE");
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.setIconTextGap(5);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateMousePressed(evt);
            }
        });
        ButtonBar.add(Update);

        Delete.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(153, 0, 0));
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/TrashCan.png"))); // NOI18N
        Delete.setLabelFor(ButtonBar);
        Delete.setText("DELETE");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.setIconTextGap(5);
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteMousePressed(evt);
            }
        });
        ButtonBar.add(Delete);

        Search.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        Search.setForeground(new java.awt.Color(153, 0, 0));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Search.png"))); // NOI18N
        Search.setLabelFor(ButtonBar);
        Search.setText("SEARCH");
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.setIconTextGap(5);
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        ButtonBar.add(Search);

        javax.swing.GroupLayout TaskManagerPageLayout = new javax.swing.GroupLayout(TaskManagerPage);
        TaskManagerPage.setLayout(TaskManagerPageLayout);
        TaskManagerPageLayout.setHorizontalGroup(
            TaskManagerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskManagerPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskManagerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(WelcomePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(ButtonBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TaskManagerPageLayout.setVerticalGroup(
            TaskManagerPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskManagerPageLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(WelcomePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        LayeredPane.add(TaskManagerPage);

        StatisticsPage.setBackground(new java.awt.Color(255, 255, 255));

        WelcomePanel2.setBackground(new java.awt.Color(180, 0, 0));

        Welcome2.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
        Welcome2.setForeground(new java.awt.Color(255, 255, 255));
        Welcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/WelcomeHand.png"))); // NOI18N
        Welcome2.setText("WELCOME OUMAIMA !");
        Welcome2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Welcome2.setIconTextGap(15);

        javax.swing.GroupLayout WelcomePanel2Layout = new javax.swing.GroupLayout(WelcomePanel2);
        WelcomePanel2.setLayout(WelcomePanel2Layout);
        WelcomePanel2Layout.setHorizontalGroup(
            WelcomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Welcome2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WelcomePanel2Layout.setVerticalGroup(
            WelcomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Welcome2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        BGPanel.setBackground(new java.awt.Color(255, 255, 255));

        DoneRatio.setForeground(new java.awt.Color(211, 0, 0));
        DoneRatio.setStringPainted(true);

        LookList.setText("Done");

        LookList1.setText("In Progress");

        InProgressRatio.setForeground(new java.awt.Color(211, 0, 0));
        InProgressRatio.setStringPainted(true);

        LookList2.setText("Not yet");

        NotYetRatio.setForeground(new java.awt.Color(211, 0, 0));
        NotYetRatio.setStringPainted(true);

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGPanelLayout.createSequentialGroup()
                        .addComponent(LookList1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InProgressRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGPanelLayout.createSequentialGroup()
                        .addComponent(LookList, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DoneRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGPanelLayout.createSequentialGroup()
                        .addComponent(LookList2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NotYetRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoneRatio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LookList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InProgressRatio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LookList1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NotYetRatio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LookList2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StatisticsPageLayout = new javax.swing.GroupLayout(StatisticsPage);
        StatisticsPage.setLayout(StatisticsPageLayout);
        StatisticsPageLayout.setHorizontalGroup(
            StatisticsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatisticsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatisticsPageLayout.setVerticalGroup(
            StatisticsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsPageLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(WelcomePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LayeredPane.add(StatisticsPage);

        Menu.setBackground(new java.awt.Color(153, 0, 0));

        IPLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IPLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/IPLogo.png"))); // NOI18N

        HomePanel.setBackground(new java.awt.Color(211, 0, 0));
        HomePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomePanelMousePressed(evt);
            }
        });

        Home1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home1.setForeground(new java.awt.Color(255, 255, 255));
        Home1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Home.png"))); // NOI18N
        Home1.setText("HOME");
        Home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home1.setIconTextGap(15);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Home1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TaskManagerPanel.setBackground(new java.awt.Color(180, 0, 0));
        TaskManagerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaskManagerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaskManagerPanelMousePressed(evt);
            }
        });

        TaskManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TaskManager.setForeground(new java.awt.Color(255, 255, 255));
        TaskManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/TaskManager.png"))); // NOI18N
        TaskManager.setText("TASK MANAGER");
        TaskManager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaskManager.setIconTextGap(15);

        javax.swing.GroupLayout TaskManagerPanelLayout = new javax.swing.GroupLayout(TaskManagerPanel);
        TaskManagerPanel.setLayout(TaskManagerPanelLayout);
        TaskManagerPanelLayout.setHorizontalGroup(
            TaskManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskManagerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TaskManager)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TaskManagerPanelLayout.setVerticalGroup(
            TaskManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskManagerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskManager, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        StatisticsPanel.setBackground(new java.awt.Color(180, 0, 0));
        StatisticsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatisticsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StatisticsPanelMousePressed(evt);
            }
        });

        Statistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Statistics.setForeground(new java.awt.Color(255, 255, 255));
        Statistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Statistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Statistics.png"))); // NOI18N
        Statistics.setText("STATISTICS");
        Statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Statistics.setIconTextGap(15);

        javax.swing.GroupLayout StatisticsPanelLayout = new javax.swing.GroupLayout(StatisticsPanel);
        StatisticsPanel.setLayout(StatisticsPanelLayout);
        StatisticsPanelLayout.setHorizontalGroup(
            StatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Statistics)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatisticsPanelLayout.setVerticalGroup(
            StatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MySeparator1.setForeground(new java.awt.Color(255, 255, 255));

        MySeparator2.setForeground(new java.awt.Color(255, 255, 255));

        AtInsat.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        AtInsat.setForeground(new java.awt.Color(255, 255, 255));
        AtInsat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Heart.png"))); // NOI18N
        AtInsat.setText("at INSAT");
        AtInsat.setIconTextGap(5);

        MadeWith.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        MadeWith.setForeground(new java.awt.Color(255, 255, 255));
        MadeWith.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MadeWith.setText("Made with");

        jPanel1.setBackground(new java.awt.Color(180, 0, 0));

        HR.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        HR.setForeground(new java.awt.Color(255, 255, 255));
        HR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HR.setText("HR");
        HR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        HR.setIconTextGap(15);

        MIN.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        MIN.setForeground(new java.awt.Color(255, 255, 255));
        MIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MIN.setText("MN");
        MIN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MIN.setIconTextGap(15);

        SEC.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        SEC.setForeground(new java.awt.Color(255, 255, 255));
        SEC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SEC.setText("SEC");
        SEC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SEC.setIconTextGap(15);

        DAY.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        DAY.setForeground(new java.awt.Color(255, 255, 255));
        DAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DAY.setText("00");
        DAY.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DAY.setIconTextGap(15);

        MONTH.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        MONTH.setForeground(new java.awt.Color(255, 255, 255));
        MONTH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MONTH.setText("00");
        MONTH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MONTH.setIconTextGap(15);

        YEAR.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        YEAR.setForeground(new java.awt.Color(255, 255, 255));
        YEAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YEAR.setText("0000");
        YEAR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        YEAR.setIconTextGap(15);

        HOUR.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        HOUR.setForeground(new java.awt.Color(255, 255, 255));
        HOUR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HOUR.setText("00");
        HOUR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        HOUR.setIconTextGap(15);

        SECOND.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        SECOND.setForeground(new java.awt.Color(255, 255, 255));
        SECOND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SECOND.setText("00");
        SECOND.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SECOND.setIconTextGap(15);

        MINUTE.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        MINUTE.setForeground(new java.awt.Color(255, 255, 255));
        MINUTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MINUTE.setText("00");
        MINUTE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MINUTE.setIconTextGap(15);

        DAY1.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        DAY1.setForeground(new java.awt.Color(255, 255, 255));
        DAY1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DAY1.setText("-");
        DAY1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DAY1.setIconTextGap(15);

        DAY2.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        DAY2.setForeground(new java.awt.Color(255, 255, 255));
        DAY2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DAY2.setText("-");
        DAY2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DAY2.setIconTextGap(15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DAY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DAY1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MONTH)
                .addGap(2, 2, 2)
                .addComponent(DAY2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YEAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HR)
                    .addComponent(HOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MINUTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SEC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SECOND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HOUR)
                            .addComponent(SECOND)
                            .addComponent(MINUTE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SEC)
                            .addComponent(MIN)
                            .addComponent(HR)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DAY)
                            .addComponent(MONTH)
                            .addComponent(YEAR)
                            .addComponent(DAY1)
                            .addComponent(DAY2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TaskManagerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StatisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addComponent(MadeWith, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AtInsat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MySeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MySeparator2)
                        .addComponent(IPLogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(IPLogoLabel)
                .addGap(18, 18, 18)
                .addComponent(MySeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(TaskManagerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(StatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MySeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MadeWith)
                    .addComponent(AtInsat))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BGLayout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(LayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BGLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        TopPanel.setBackground(new java.awt.Color(180, 0, 0));
        TopPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        TopPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopPanelMouseDragged(evt);
            }
        });
        TopPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TopPanelMousePressed(evt);
            }
        });

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Close.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setIconTextGap(15);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        Icon.setFont(new java.awt.Font("Comfortaa", 1, 14)); // NOI18N
        Icon.setForeground(new java.awt.Color(255, 255, 255));
        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/Webp.net-resizeimage (6).png"))); // NOI18N
        Icon.setText("Insat Press Task Manager");
        Icon.setAlignmentY(0.0F);
        Icon.setIconTextGap(8);

        Screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/FullScreen.png"))); // NOI18N
        Screen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Screen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 631, Short.MAX_VALUE)
                .addComponent(Screen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Home)
                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 11, Short.MAX_VALUE))
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMousePressed
        setColor(HomePanel);
        resetColor(TaskManagerPanel);
        resetColor(StatisticsPanel);
        TaskManagerPage.setVisible(false) ;
        HomePage.setVisible(true) ;
        StatisticsPage.setVisible(false);
        
    }//GEN-LAST:event_HomePanelMousePressed

    private void TaskManagerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskManagerPanelMousePressed
        resetColor(HomePanel);
        setColor(TaskManagerPanel);
        resetColor(StatisticsPanel);
        TaskManagerPage.setVisible(true) ;
        HomePage.setVisible(false) ;
        StatisticsPage.setVisible(false);
        
    }//GEN-LAST:event_TaskManagerPanelMousePressed

    private void StatisticsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticsPanelMousePressed
        resetColor(HomePanel);
        resetColor(TaskManagerPanel);
        setColor(StatisticsPanel);
        TaskManagerPage.setVisible(false) ;
        HomePage.setVisible(false) ;
        StatisticsPage.setVisible(true);
    }//GEN-LAST:event_StatisticsPanelMousePressed

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        System.exit(0) ;
    }//GEN-LAST:event_HomeMousePressed

    int xx ;
    int yy ;
    
    private void TopPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopPanelMouseDragged
        /*DragListener dl = new DragListener() ;
        dl.mouseDragged(evt) ;*/
        int x = evt.getXOnScreen() ;
        int y = evt.getYOnScreen() ;
        this.setLocation(x-xx,y-yy);
        
    }//GEN-LAST:event_TopPanelMouseDragged

    private void TopPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopPanelMousePressed
        xx = evt.getX() ;
        yy = evt.getY() ;
    }//GEN-LAST:event_TopPanelMousePressed

    private void ScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenMouseClicked
        if (Maximized)
        { 
            Frame.this.setExtendedState(JFrame.MAXIMIZED_BOTH) ;
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment() ;
            Frame.this.setMaximizedBounds( env.getMaximumWindowBounds() );
            Screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/NormalScreen.png")));
            Maximized = false ;
        }
        else
        {
            setExtendedState(JFrame.NORMAL) ;
            Maximized = true ;
            Screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iptaskmanager/Images/FullScreen.png")));
        }
    }//GEN-LAST:event_ScreenMouseClicked

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update.setText("UPDATE");
    }//GEN-LAST:event_UpdateMouseExited

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update.setText("UPDATE ME");
    }//GEN-LAST:event_UpdateMouseEntered

    private void CREATEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEMousePressed
        
    
        TaskID.setText("");
        Task.setText("Task");
        Date.setText("yyyy-mm-dd");
        Deadline.setText("yyyy-mm-dd");
        PIC.setText("Person in charge");
        State.setSelectedIndex(-1);
        
        
      
    }//GEN-LAST:event_CREATEMousePressed

    private void CREATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEMouseEntered
        CREATE.setText("CREATE ME");
    }//GEN-LAST:event_CREATEMouseEntered

    private void CREATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEMouseExited
        CREATE.setText("CREATE");
    }//GEN-LAST:event_CREATEMouseExited

    private void UpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMousePressed
            int gtid = Integer.parseInt(TaskID.getText()) ;
            String gt = Task.getText() ;
            String gdt = Date.getText() ;
            String gdd = Deadline.getText() ;
            String gpic = PIC.getText() ;
            String gs = State.getSelectedItem().toString() ;
            
            UpdateDataControl udc = new UpdateDataControl();
            udc.updateTask(gtid,gt, gdt, gdd, gpic, gs);
            loadInitial() ;
        
    }//GEN-LAST:event_UpdateMousePressed

    private void TaskTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskTableMousePressed
        fill();
    }//GEN-LAST:event_TaskTableMousePressed

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete.setText("DELETE ME");
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete.setText("DELETE");
    }//GEN-LAST:event_DeleteMouseExited

    private void DeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMousePressed
      int gtid = Integer.parseInt(TaskID.getText()) ;
      UpdateDataControl udc = new UpdateDataControl();
      udc.deleteTask(gtid);
      loadInitial() ;
      
    }//GEN-LAST:event_DeleteMousePressed

    private void SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseEntered
        Save.setText("SAVE ME");
    }//GEN-LAST:event_SaveMouseEntered

    private void SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseExited
        Save.setText("SAVE");
    }//GEN-LAST:event_SaveMouseExited

    private void SaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMousePressed
        
            String gtid = TaskID.getText() ;
            String gt = Task.getText() ;
            String gdt = Date.getText() ;
            String gdd = Deadline.getText() ;
            String gpic = PIC.getText() ;
            String gs = State.getSelectedItem().toString() ;
            
            UpdateDataControl udc = new UpdateDataControl();
            udc.saveTask(gt, gdt, gdd, gpic, gs);
            loadInitial() ;

    }//GEN-LAST:event_SaveMousePressed

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
       Search.setText("SEARCH ME");
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseExited
        Search.setText("SEARCH");
    }//GEN-LAST:event_SearchMouseExited

    private void SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMousePressed
        String gt = Task.getText() ;
            String gdt = Date.getText() ;
            String gdd = Deadline.getText() ;
            String gpic = PIC.getText() ;
            String gs = State.getSelectedItem().toString() ;
            
            ImportDataControl idc = new ImportDataControl();
            ResultSet rs = idc.searchTask(gt, gdt, gdd, gpic, gs);
            fillTable(TaskTable,rs) ;
    }//GEN-LAST:event_SearchMousePressed

    private void BGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMousePressed
        loadInitial() ;
    }//GEN-LAST:event_BGMousePressed

    private void ComingSoonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComingSoonTableMouseClicked
        int r = ComingSoonTable.getSelectedRow() ;
        int id = (int) ComingSoonTable.getValueAt(r, 0) ;
        
        int rc = TaskTable.getRowCount() ;
        int i=0;
        int lid=(int)TaskTable.getValueAt(0,0);
        while( (lid!=id) && (i<=rc) )
        {
            i++ ;
            lid=(int)TaskTable.getValueAt(i,0);
        }
        
        
        TaskTable.setRowSelectionInterval(i, i);
        
        resetColor(HomePanel);
        setColor(TaskManagerPanel);
        resetColor(StatisticsPanel);
        TaskManagerPage.setVisible(true) ;
        HomePage.setVisible(false) ;
        StatisticsPage.setVisible(false);
    }//GEN-LAST:event_ComingSoonTableMouseClicked
     
    /**
     * @param args the command line arguments
     */
    
    
    void setColor(javax.swing.JPanel panel) { panel.setBackground( new java.awt.Color(211,0,0) ) ; }
    
    void resetColor(javax.swing.JPanel panel) { panel.setBackground( new java.awt.Color(180,0,0) ) ; }
    
    void fillTable(JTable table, ResultSet rs)
    {
         while ( table.getRowCount() > 0 )
            {
                ((DefaultTableModel)table.getModel()).removeRow(0) ;
            }
           
        try {
            
             int col = rs.getMetaData().getColumnCount() ;
            
            while ( rs.next() )
            {
                int id = rs.getInt("id") ;
                String task = rs.getString("task") ;
                String date = rs.getString("date") ;
                String deadline = rs.getString("deadline") ;
                String pic = rs.getString("PersonInCharge") ;
                String state = rs.getString("state") ;
                
                Object[] o = new Object[]{id,task,date,deadline,pic,state} ;
                ((DefaultTableModel)table.getModel()).addRow(o) ;
            }
            
            
        } catch (Exception ex) {
            
        }
    }
    void loadInitial()
    {   ImportDataControl idc = new ImportDataControl() ;
        ResultSet rs = idc.loadAllTasks() ;
        fillTable(TaskTable,rs);
        int c =0;
        try {
            rs.last();
            c = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        LocalDateTime ldt = LocalDateTime.now() ;
            
            int dd = ldt.getDayOfMonth() ;
            String ddy = String.valueOf( dd ) ;
            if ( dd<10 ) 
                ddy = '0'+ddy ;
            
            int mth = ldt.getMonthValue() ;
            String mmth = String.valueOf(mth) ;
            if ( mth<10 ) 
                mmth = '0'+mmth ;

            String str = String.valueOf( ldt.getYear() )+"-"+mmth+"-"+ddy ;
        
        rs = idc.loadTasksToday(str) ;
        fillTable(ComingSoonTable,rs);
        
        int count =0 ;
        
        rs = idc.taskState("Done") ;
        try {
            rs.last();
            count = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        int dr = count*100/c;
        DoneRatio.setValue(dr);
        
        rs = idc.taskState("In progress") ;
        try {
            rs.last();
            count = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ipr = count*100/c;
        InProgressRatio.setValue(ipr);
        
        rs = idc.taskState("Not yet") ;
        try {
            rs.last();
            count = rs.getRow();
        } catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ny = count*100/c;
        NotYetRatio.setValue(ny);
        
    }
   
    
    void fill ()
    {
        int r = TaskTable.getSelectedRow() ;
        String tid =  (TaskTable.getValueAt(r,0)).toString() ;
        TaskID.setText(tid);
        String ts =  (TaskTable.getValueAt(r,1)).toString() ;
        Task.setText(ts);
        String dt =  (TaskTable.getValueAt(r,2)).toString() ;
        Date.setText(dt);
        String dd =  (TaskTable.getValueAt(r,3)).toString() ;
        Deadline.setText(dd);
        String pic =  (TaskTable.getValueAt(r,4)).toString() ;
        PIC.setText(pic);
        String state =  (TaskTable.getValueAt(r,5)).toString() ;
        State.setSelectedItem(state);
        
    }
    
     
    /*private class DragListener extends MouseAdapter
    {
        public void mouseDragged ( MouseEvent e)
        {
            setLocation( MouseInfo.getPointerInfo().getLocation() ) ;
        }
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AtInsat;
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JPanel ButtonBar;
    private javax.swing.JLabel CREATE;
    private javax.swing.JTable ComingSoonTable;
    private javax.swing.JLabel DAY;
    private javax.swing.JLabel DAY1;
    private javax.swing.JLabel DAY2;
    private javax.swing.JFormattedTextField Date;
    private javax.swing.JFormattedTextField Deadline;
    private javax.swing.JLabel Delete;
    private javax.swing.JProgressBar DoneRatio;
    private javax.swing.JPanel EditingBar;
    private javax.swing.JLabel HOUR;
    private javax.swing.JLabel HR;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JPanel HomePage;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel IPLogoLabel;
    private javax.swing.JLabel Icon;
    private javax.swing.JProgressBar InProgressRatio;
    private javax.swing.JPanel LayeredPane;
    private javax.swing.JLabel LookList;
    private javax.swing.JLabel LookList1;
    private javax.swing.JLabel LookList2;
    private javax.swing.JLabel MIN;
    private javax.swing.JLabel MINUTE;
    private javax.swing.JLabel MONTH;
    private javax.swing.JLabel MadeWith;
    private javax.swing.JPanel Menu;
    private javax.swing.JScrollPane MyScrollPane;
    private javax.swing.JScrollPane MyScrollPane1;
    private javax.swing.JSeparator MySeparator1;
    private javax.swing.JSeparator MySeparator2;
    private javax.swing.JProgressBar NotYetRatio;
    private javax.swing.JTextField PIC;
    private javax.swing.JLabel SEC;
    private javax.swing.JLabel SECOND;
    private javax.swing.JLabel Save;
    private javax.swing.JLabel Screen;
    private javax.swing.JLabel Search;
    private javax.swing.JComboBox<String> State;
    private javax.swing.JLabel Statistics;
    private javax.swing.JPanel StatisticsPage;
    private javax.swing.JPanel StatisticsPanel;
    private javax.swing.JTextField Task;
    private javax.swing.JTextField TaskID;
    private javax.swing.JLabel TaskManager;
    private javax.swing.JPanel TaskManagerPage;
    private javax.swing.JPanel TaskManagerPanel;
    private javax.swing.JTable TaskTable;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel Welcome1;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JLabel Welcome3;
    private javax.swing.JLabel Welcome4;
    private javax.swing.JPanel WelcomePanel1;
    private javax.swing.JPanel WelcomePanel2;
    private javax.swing.JPanel WelcomePanel3;
    private javax.swing.JLabel YEAR;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
